### ISSUE TITLE
Issue when using -i 

### ISSUE THREAD

**Issue by math-ematics** [s0md3v/Arjun#102]
Just installed newest version from *.tar
Installed/ updated everything pip3 install --upgrade requests since there were an error thrown
`RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!`

using -u works.
When using txt file with subdomains that has been ran thru httpx it throws this error.
`
[*] Probing the target for stability
Traceback (most recent call last):
  File "arjun.py", line 179, in <module>
    these_params = initialize(each, list(wordlist))
  File "arjun.py", line 126, in initialize
    response_1 = requester(request, {fuzz : fuzz[::-1]})
  File "/root/tools/Arjun-2.0-beta/core/requester.py", line 15, in requester
    if request['include']:
KeyError: 'include'
`

Using git clone for the repo everything works perfectly. but the 2.0 tar file have issues

**Comment by s0md3v** [comment]
Well, that was an early beta release, now those bugs have been fixed so please clone the repo directly.

Anyways, this week a new release will be available.
