### ISSUE TITLE
Cant run arjun.py

### ISSUE THREAD

**Issue by TheSkyLookingGood** [s0md3v/Arjun#105]
Error: 

> ImportError: cannot import name 'res' from 'core.colors'

https://github.com/s0md3v/Arjun/blob/d9af0f86a9812afe6dce8828c878005571dcd306/arjun.py#L6
i assume is mistyped from "red"

**Comment by s0md3v** [comment]
No, `res` is intended. Are you sure you are using the latest git version?

**Comment by f1w** [comment]
https://github.com/s0md3v/Arjun/releases/tag/2.0-beta

![image](https://user-images.githubusercontent.com/73308423/103295552-8361ba80-49f4-11eb-8172-d8dc460a4a37.png)

This Error  only occurs when downloading from this page i'm pretty sure.

**Comment by s0md3v** [comment]
Yep, that was the initial beta release, full of bugs.

Clone the repo instead.
