### ISSUE TITLE
non-latin characters in parameter names cause error

### ISSUE THREAD

**Issue by tXambe** [s0md3v/Arjun#108]
Hello,

When I run Arjun I have this error:

```
sudo python3 arjun.py -u https://example.com -m GET -w /usr/share/wordlists/seclists/Discovery/Variables/secret-keywords.txt 

Traceback (most recent call last):
  File "/opt/API/Arjun/arjun.py", line 171, in <module>
    these_params = initialize(request, wordlist)
  File "/opt/API/Arjun/arjun.py", line 160, in initialize
    print('%s name: %s, factor: %s' % (res, name, reason))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2713' in position 8: ordinal not in range(256)

```
Can anyone help me ?

A greeting and thanks

**Comment by tXambe** [comment]
Hello,

The version is 1.6

A greeting

**Comment by VainlyStrain** [comment]
Hi! This error usually means that your terminal environment doesn't support UTF8 (which is used by Arjun). A possible fix would be to remove non-ascii characters in the output strings.

**Comment by s0md3v** [comment]
Looks like this problem is not related to Arjun as explained by @VainlyStrain, closing.

If even running it an utf-8 environment gives an error, we can re-open this issue.

**Comment by fadyosman** [comment]
If anyone is wondering how to fix this, you need to enable UTF-8 as described [Here](https://unix.stackexchange.com/questions/303712/how-can-i-enable-utf-8-support-in-the-linux-console) in the answer by [GAD3R](https://unix.stackexchange.com/users/153195/gad3r)


Check that you have the `locales` package installed

    dpkg -l locales

If not, install it

    apt-get install locales


As root, type

    dpkg-reconfigure locales

you can navigate that list with the up/down arrow keys, for example choose `en_US-UTF-8`

edit your `.bashrc` by adding the following lines:

    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LANGUAGE=en_US.UTF-8
Run  the `locale`command ,the output should be similar to this::

    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=
