### ISSUE TITLE
chunk size error

### ISSUE THREAD

**Issue by Naategh** [s0md3v/Arjun#112]
I don't know what's wrong with new versions of Arjun but with any URL and any chunk size that I try, I'm getting this error
```
[-] Server recieved a bad request. Try decreasing the chunk size with -c option
[-] Skipped URL due to errors
```

**Comment by s0md3v** [comment]
Hi,

I am unable to reproduce this on my system. Is it possible for you to share a URL where this happens?
You can message me on [my twitter](https://twitter.com/s0md3v) or mail me at s0md3v@gmail.com
