### ISSUE TITLE
setup.py file error while installing arjun

### ISSUE THREAD

**Issue by blackdaliyadali** [s0md3v/Arjun#113]
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

this is the error
my python version is 3.8.6

**Comment by s0md3v** [comment]
```
python3 setup.py install
```
