### ISSUE TITLE
Why was the pip installation removed from the docs?

### ISSUE THREAD

**Issue by VainlyStrain** [s0md3v/Arjun#114]
Hi!

I'd only like to ask why the pip installation instructions were removed from the docs. As one of my projects depends on arjun, it is included in the requirements.txt file, which will fetch from pypi via pip. Will this way of installing be discontinued?

Greetings!
VS

**Comment by s0md3v** [comment]
Using pip with sudo to install Arjun causes an error which I believe to be
in pip's latest itself so I have removed it for now from the docs but you
can still use it, it's not discontinued.

**Comment by VainlyStrain** [comment]
All right, thanks!
