### ISSUE TITLE
Quiet mode or similar to ouput results on STDOUT too

### ISSUE THREAD

**Issue by TvMpt** [s0md3v/Arjun#115]
Hi,

is it possible that -q option, or new parameter, that sends the output to STDOUT, instead having to use an output file?
Regards,
Pedro

**Comment by TvMpt** [comment]
Sorry, didn't notice that you included in last version.

**Comment by s0md3v** [comment]
Sure we can have that, I have been thinking about that too.

**Comment by s0md3v** [comment]
closing this as a `-q/--quiet` option was added in version 2.1.0
