### ISSUE TITLE
The specified file for parameters doesn't exist

### ISSUE THREAD

**Issue by Youghourta-ghennai** [s0md3v/Arjun#120]
when i installed Arjun successfully in my windows 10 , when I try to use it with any parameter like : 
arjun -u URL or 
arjun -i list.txt I got this error ### The specified file for parameters doesn't exist ,
except the --help parameter it works properly fine .

**Comment by s0md3v** [comment]
Hey,

The issue should be fixed now. I do not have windows to test this, let me know if it's still not working.

Thanks for reporting!

**Comment by Youghourta-ghennai** [comment]
i think i find where is the problem dude , if you want me to post it now , I will do it .

**Comment by s0md3v** [comment]
Yes, please!

**Comment by Youghourta-ghennai** [comment]
yeah but i tried it on the old version of arjun , because I had the same problem , 
this is the version that I have tried the solution on it  : https://github.com/Alexxino/Arjun

**Comment by Youghourta-ghennai** [comment]
it is easy  : 

1. cd Arjun
2. C:\Python3\python.exe arjun.py -u https://www.test.dz/endpoint
i hope you understand it .
