### ISSUE TITLE
chunk size error: for 400 bad request?

### ISSUE THREAD

**Issue by sA74n** [s0md3v/Arjun#121]
Server recieved a bad request. Try decreasing the chunk size with -c option

**Comment by s0md3v** [comment]
As it says, decrease the chunk size. If that doesn't work, let me know.

**Comment by sA74n** [comment]
I have tried it...but doesn't work for me

**Comment by s0md3v** [comment]
Okay, is this possible for you to share the target URL in private so I can reproduce it?

**Comment by sA74n** [comment]
sure
