### ISSUE TITLE
arjun does not parse raw file

### ISSUE THREAD

**Issue by mohammed-sec2010** [s0md3v/Arjun#125]
command 
arjun -i /opt/toolsafterburp/dumpBurpDivided/post/postrequest1.txt 

result : 
   _
   /_| _ '
  (  |/ /(//) v2.1.1
      _/      

Traceback (most recent call last):
  File "/usr/local/bin/arjun", line 33, in <module>
    sys.exit(load_entry_point('arjun==2.1.1', 'console_scripts', 'arjun')())
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.1-py3.8.egg/arjun/__main__.py", line 159, in main
    url = request['url']
KeyError: 'url'

**Comment by mohammed-sec2010** [comment]
raw file:
GET /mutillidae/index.php?page=dns-lookup.php HTTP/1.1
Host: 192.168.1.154
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: PHPSESSID=d40bf383297e3fb7720da3070f9054ad
Connection: close

**Comment by s0md3v** [comment]
Thanks for reporting, I am looking into it.

**Comment by mohammed-sec2010** [comment]
any updates?
