### ISSUE TITLE
Runs out of memory on some websites

### ISSUE THREAD

**Issue by Sh1Yo** [s0md3v/Arjun#129]
OS: `Linux arch 5.10.8-arch1-1 #1 SMP PREEMPT Sun, 17 Jan 2021 22:07:13 +0000 x86_64 GNU/Linux`

Steps To Reproduce:
`echo something > 1`
`arjun -w 1 -u https://www.pixiv.net/en/ `

```
    _
   /_| _ '
  (  |/ /(//) v2.1.1
      _/      

[*] Probing the target for stability
[*] Analysing HTTP response for anamolies
[1]    752651 killed     arjun -w 1 -u https://www.pixiv.net/en/
```
Arjun keeps filling memory until OS kills the process.

Affected urls I've found:
`https://yandex.ru/`
`https://ya.ru/`
`https://www.pixiv.net/en/`

**Comment by s0md3v** [comment]
damn, this goes on priority.
