### ISSUE TITLE
Implement Alternate Input Vectors

### ISSUE THREAD

**Issue by decal** [s0md3v/Arjun#13]
Create command-line options for optionally testing unusual CGI input vectors as I mentioned in a tweet: 

<https://twitter.com/decalresponds/status/1101813400487620610>

> support for more HTTP verbs & param syntaxes, i.e. pass query params with script path in POST, as multipart form data, query string arrays, fragment vars, etc.

<https://stackoverflow.com/questions/611906/http-post-with-url-query-parameters-good-idea-or-not>

```
POST /cgi-bin/a.cgi?avar=aval
Host: host.dom
Content-Length: 0
Connection: Keep-Alive
User-Agent: MSIE
```

<https://ec.haxx.se/http-multipart.html>

```
POST /cgi-bin/a.cgi
Host: host.dom
Content-Length: X
Content-Type: multipart/form-data; boundary=AaB03x

--AaB03x
Content-Disposition: form-data; name="avar"

aval
--AaB03x
```
<https://www.npmjs.com/package/query-string>

```
GET /cgi-bin/a.cgi?avar[]=1&avar[]=2
Host: host.dom
User-Agent: MSIE
Connection: Keep-Alive
```
   
_Adding additional input vectors as they come to mind in the comment below.._

**Comment by decal** [comment]
Option to send query variable definitions in the body of a non-POST request sent with a **_Content-Length_** request header (should this include DAV methods?) . For instance:

GET / HTTP/1.1
Host: host.dom
Content-Length: 15
User-Agent: MSIE
Connection: Keep-Alive

x=2&avar=tested

**Comment by decal** [comment]
Add a command-line option that separates query parameters with semi-colons instead of ampersands as specified in the W3C document linked below:

<https://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2>

**Comment by decal** [comment]
Test for reverse proxies (or other middle-boxes)  between the browser and back-end by percent-encoding the variable names/values themselves or ampersands/semi-colons acting as field separators between multiple query parameter bindings.

**Comment by decal** [comment]
Check for "flag-style" behavior of query parameters.  For example, how are requests for the paths below handled? 

* /cgi-bin/a.cgi?atest=1
* /cgi-bin/a.cgi?atest

**Comment by decal** [comment]
Implement [RFC6570](https://tools.ietf.org/html/rfc6570 "URI Template") style expressions

**Comment by s0md3v** [comment]
Hi @decal ,

Thanks for all the suggestions.
Would it be possible for you to contribute by pull requests in your free time?
It's okay if you can't.

**Comment by s0md3v** [comment]
Hi @decal ,

Would you like to work on it?
