### ISSUE TITLE
so much results

### ISSUE THREAD

**Issue by Phoenix1112** [s0md3v/Arjun#132]
thanks for this project. I am seeing too many results. This is probably because all parameter names in the wordlist appear to be reflected. here the arjun program needs to do a test. for example, it should try something of any words as a preliminary review. if it is not reflected, it should try other parameters in the wordlist. Since whatever you type in the parameter name is reflected, the Arjun program outputs the whole wordlist as output. When I run this with the burp suite output file, I wait for it to finish for hours because I cannot cancel it in such cases. It prints all the words in the wordlist as a result, as seen below.

![image](https://user-images.githubusercontent.com/42475284/117368833-b816de80-aecc-11eb-91ab-d0213a3b72c8.png)

I have another problem. I'm starting the arjun program on the burp output. I'm trying to proxy the arjun output using the -oB parameter. However, after Arjun finds the parameters of a few url addresses, it passes to the next url address instead of proxying. Meanwhile, it causes the burp suite program to remain open and idle for hours. so I think it would be useful to proxy before moving on to the next url.

**Comment by s0md3v** [comment]
Hey Phoenix,

Can you please share the URL where you found this issue in private? You DM me on my [twitter](https://twitter.com/s0md3v) or mail me at s0md3v [at] gmail [dot] com

Thanks for reporting and suggestions regarding how to proceed with this.

**Comment by Phoenix1112** [comment]
Thank you for the answer. I just sent you a mail.

**Comment by Phoenix1112** [comment]
@s0md3v another problem!! .. I thought it would make more sense to first print the output to txt file instead of burp proxy. For example, suppose we run arjun on the burp output file containing 15 urls. After successfully scanning 7 url addresses, it went to the 8th url address. While testing this, I got a python request error or timeout error and the arjun program terminated. When I searched for the output file of successful url addresses, I saw that arjun did not record it. So again, arjun is waiting for all url addresses to be finished. here is an example error.

```
[*] Probing the target for stability
[*] Analysing HTTP response for anamolies
[*] Analysing HTTP response for potential parameter names
[+] Heuristic scanner found 34 parameters: ctl00_ScriptManager1_HiddenField, __EVENTTARGET, __EVENTARGUMENT, __VIEWSTATE, __VIEWSTATEGENERATOR, __VIEWSTATEENCRYPTED, __PREVIOUSPAGE, beacon, errorbeacon, licensekey, applicationid, transactionname, agent, atts, n, g, 443, hidden, act_tab, couponcode, display, couponcodetext, couponcodehtml, couponinlinetext, upgradetoplan, associatedupdatepanelid, clientstatefieldid, collapsecontrolid, expandcontrolid, id, backgroundcssclass, cancelcontrolid, popupcontrolid, dynamicservicepath
[*] Logicforcing the URL endpoint
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Connection timed out, increased timeout by 5 seconds
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Encountered an error: app.anymeeting.com
[-] Connection timed out, increased timeout by 5 seconds
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further
Traceback (most recent call last):
  File "/usr/local/bin/arjun", line 33, in <module>
    sys.exit(load_entry_point('arjun==2.1.1', 'console_scripts', 'arjun')())
  File "/usr/local/lib/python3.9/dist-packages/arjun-2.1.1-py3.9.egg/arjun/__main__.py", line 174, in main
    these_params = initialize(each, list(wordlist))
  File "/usr/local/lib/python3.9/dist-packages/arjun-2.1.1-py3.9.egg/arjun/__main__.py", line 134, in initialize
    param_groups = narrower(request, factors, param_groups)
  File "/usr/local/lib/python3.9/dist-packages/arjun-2.1.1-py3.9.egg/arjun/__main__.py", line 94, in narrower
    if result.result():
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
%s Connection timed out, unable to increase timeout further
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/arjun-2.1.1-py3.9.egg/arjun/core/bruter.py", line 21, in bruter
    comparison_result = compare(response, factors, params)
  File "/usr/local/lib/python3.9/dist-packages/arjun-2.1.1-py3.9.egg/arjun/core/anomaly.py", line 52, in compare
    if factors['same_code'] and response.status_code != factors['same_code']:
AttributeError: 'str' object has no attribute 'status_code'
%s Connection timed out, unable to increase timeout further
%s Connection timed out, unable to increase timeout further

```

When you end up with an error, python "except" doesn't come into play.

**Comment by s0md3v** [comment]
This has been fixed as per my testing. If you face this problem again, feel free to re-open this issue.

**Comment by Phoenix1112** [comment]
@s0md3v With the -oT parameter, it does not give the output at the end of every url.. For example, I'm running it on burp output, but it waits for all url addresses to be finished to output. I can't see any output when we end the program when we have an urgent job and want to shut down the computer. After scanning each new url address, arjun should save the results it finds in a txt file before moving on to the next url address.
