### ISSUE TITLE
Missing & between parameters on text export results

### ISSUE THREAD

**Issue by leorac** [s0md3v/Arjun#136]
Just trying the text export result, it looks like it craft a string like that https://www.target.com/param1=test1param2=test2param3=test3 forgetting to put an & and between the parameters and making the output unusable

**Comment by leorac** [comment]
And of course it would be better to have a text export as simple list of params

**Comment by leorac** [comment]
Of course it would be good to also have a text export as a simple list of params

**Comment by s0md3v** [comment]
This bug has been fixed in the git build but not pypi, please install it manually or wait for the next release.
