### ISSUE TITLE
Detect HTTP Parameter Pollution

### ISSUE THREAD

**Issue by decal** [s0md3v/Arjun#14]
When a new parameter name is discovered, test for its existence in the opposite HTTP method (i.e. if it was found in GET, try POST or vice versa.)  Optionally test other RFC-specified and/or user-defined HTTP verbs..

**Comment by s0md3v** [comment]
I guess that will open a window for a lot of other checks which I don't really want because Arjun is parameter discovery suite and let's keep it to that.
Thanks for the suggestion
