### ISSUE TITLE
Invalid default `arjun_dir` in Windows

### ISSUE THREAD

**Issue by AntonyGarand** [s0md3v/Arjun#141]
Under Windows, the path is separated by backslashes instead of forward slashes, making the path invalid:
```python
arjun_dir = compatible_path(mem.__file__.replace('/core/config.py', ''))
```
The `mem.__file__` value is `c:\python39\lib\site-packages\arjun\core\config.py` in my case.

An easy fix would be to replace all backslashed by forward slashes before doing the final replace.

**Comment by s0md3v** [comment]
This has been resolved, [here](https://github.com/s0md3v/Arjun/commit/3bf0da5ddc6e1c60ab1a0cb205491fbb20979d3b).

Thanks for reporting the issue 🎉
