### ISSUE TITLE
There are deficiencies in the working logic.

### ISSUE THREAD

**Issue by Phoenix1112** [s0md3v/Arjun#160]
hello. thanks for this project. arjun is a program that helps to find usable parameters on the url addresses we give. but if there is a default parameter in the url provided by the user, arjun will ignore this parameter and start working that way.

For example, let's assume that a url is given by the user as follows.

```
https://arjun.com/blabla
```

That's exactly how arjun parameters are called.

```
https://arjun.com/blabla?fuzz-parametres=1
```

so how does arjun behave if a parameter is provided by default by the user?

orginal url:

```
https://arjun.com/blabla?cat=1
```

arjun will work as follows for such a url.

```
https://arjun.com/blabla?fuzz-parametres=1
```

The actual trial method should be as follows.

```
https://arjun.com/blabla?cat=1&fuzz-parametres=1
```

How did I know that this method is really the correct method? 

First of all, I was testing a target manually and there were two parameters in the url.

```?errorcode=kamil&message=test```

the ```message``` parameter above was reflected in the source code. When I test on the same url as arjun, no parameters were found. whereas the parameter ```message``` is a word in the arjun wordlist. When I tested why it couldn't find it, I understood that if the other parameter in the url is not in the url, the other parameter is not reflected. ```?errorcode=```

if there is ```?errorcode=``` parameter in the url, the ```message``` parameter is reflected. If not, the ```message``` parameter is not reflected. so I re-executed the arjun program with the ```?errorcode=``` parameter. but arjun still couldn't find the ```message``` parameter.  because arjun deletes ```?any-parameter=``` parameter in the url when starting the program.

Therefore, there is a mistake in the working logic of the program.

**Comment by s0md3v** [comment]
Hi @Phoenix1112,

Thanks for this detailed bug report!
However, I am not able to reproduce it. Arjun is using the user-provided parameters properly.

![image](https://user-images.githubusercontent.com/26716802/164704367-32128a3c-774b-4cd6-83d3-1fa25cc26dc0.png)

Is it possible for you to share the target privately with me? You can DM me on [twitter](https://twitter.com/s0md3v) or send me a mail at s0md3v @ gmail.com

**Comment by Phoenix1112** [comment]
@s0md3v Thank you for your answer. When I examine the commands you use, I see that you are using the ```--include``` parameter.  I have never used it this way before. but when I test it like this, the ```message``` parameter is found. previously I used a command exactly like the one below.

```
arjun -u https://arjun.com/blabla?errorcode=kamil
```

Are you saying that the ``--include``` parameter is mandatory to be used in the command? if not mandatory i can send you the real url from twitter dm. If you say that the ```--include``` parameter is mandatory for such cases, you can close this ticket.

**Comment by s0md3v** [comment]
bruh. Did you even read the documentation?

Obviously `--include` is mandatory.

**Comment by Phoenix1112** [comment]
@s0md3v Honestly, I read the documents last year and it never occurred to me right now. also this is the first time i test a url address like this. Anyway, thank you for spending your precious time with me.
