### ISSUE TITLE
[Improvement] Minimal Progress status

### ISSUE THREAD

**Issue by alvaara** [s0md3v/Arjun#164]
Hi! Just wanted to suggest a minimal progress status upon pressing some key or once every few scanned elements. It becomes nice to have when testing large ammounts of urls.

Something like "546 of 1340 lines(URLs) tested..." would be great to have.

**Comment by s0md3v** [comment]
A url progress counter has been added in Arjun v2.1.6 🎉

**Comment by alvaara** [comment]
neeat
