### ISSUE TITLE
TypeError: 'method' object is not subscriptable

### ISSUE THREAD

**Issue by welltest** [s0md3v/Arjun#166]
arjun -i /root/abc.com/abc.com_httpx -m GET -oT param.txt 

![2022-08-03 18_20_25-Search · TypeError_ 'method' object is not subscriptable](https://user-images.githubusercontent.com/7748482/182612192-2e640229-4723-44b7-8c50-555db54f3ab7.png)

**Comment by bl1lnk** [comment]
any update ?

**Comment by bl1lnk** [comment]
i had the same issue and this  fixed my  problem 
1- cat target.txt | httpx >> final_target.txt
2- arjun -i  target.txt

**Comment by bl1lnk** [comment]
any update ?

**Comment by s0md3v** [comment]
This issue has been fixed in Arjun 2.1.6 🎉

Thanks for reporting!
