### ISSUE TITLE
Request - add auth login or cookies option to Arjun

### ISSUE THREAD

**Issue by CostyCrypto** [s0md3v/Arjun#169]
We need to add an option to the scanner to make it login on the website to access some page you can't access it without login

**live example on a demo php script**

you can't access this page

https://demo.activeitzone.com/matrimonial/member-listing

without login

https://demo.activeitzone.com/matrimonial/users/login

If you run Arjun on the demo php script website i showed up it will crawl the index and all pages without the "member-listing" page cause you don't have credential access 

**live scan on the website**

**test.txt**

GET /matrimonial/member-listing?age_from=22&age_to=66&member_code=&marital_status=&religion_id=1&caste_id=1&sub_caste_id=&mother_tongue=1&profession=&country_id=121&state_id=2150&city_id=26025&min_height=1&max_height=2&member_type=0 HTTP/2
Host: demo.activeitzone.com
Cookie: XSRF-TOKEN=2X8QbgsB7YrCbTYLC8QiPW44Diw3TSM5RdgnVrCl; testing_session=gSnyluxLaee13csXLxgJvV4apzmyPqnmBcMCqIbH; acceptCookies=true
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://demo.activeitzone.com/matrimonial/member-listing
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Te: trailers

**[scanning start]**

arjun -i test.txt

Probing the target for stability
 Analysing HTTP response for anomalies
 Analysing HTTP response for potential parameter names
 Heuristic scanner found 2 parameters: deacticvation_status, _token
 Logicforcing the URL endpoint
 name: deacticvation_status, factor: param name reflection
 name: _token, factor: param name reflection

**as we see all this parameters not detected**

age_from=22&age_to=66&member_code=&marital_status=&religion_id=1&caste_id=1&sub_caste_id=&mother_tongue=1&profession=&country_id=121&state_id=2150&city_id=26025&min_height=1&max_height=2&member_type=0

**Comment by s0md3v** [comment]
use `--headers` option

**Comment by CostyCrypto** [comment]
Thank you a lot for you fast respond can you guide me where's my fault cause still not catching the **parameters**

age_from=22&age_to=66&member_code=&marital_status=&religion_id=1&caste_id=1&sub_caste_id=&mother_tongue=1&profession=&country_id=121&state_id=2150&city_id=26025&min_height=1&max_height=2&member_type=0


arjun -i marti.txt --headers "Accept-Language: en-US\nCookie: null" -oB 127.0.0.1:8080
    _
   /_| _ '
  (  |/ /(//) v2.1.51
      _/

 Probing the target for stability
 Analysing HTTP response for anomalies
 Analysing HTTP response for potential parameter names
 Heuristic scanner found 2 parameters: deacticvation_status, _token
 Logicforcing the URL endpoint
 name: deacticvation_status, factor: param name reflection
 name: _token, factor: param name reflection

C:\Users\Pentest\Desktop\Arjun>arjun -u https://demo.activeitzone.com/matrimonial/member-listing --headers "Accept-Language: en-US\nCookie: XSRF-TOKEN=2X8QbgsB7YrCbTYLC8QiPW44Diw3TSM5RdgnVrCl;" -oB 127.0.0.1:8080
    _
   /_| _ '
  (  |/ /(//) v2.1.51
      _/

 Probing the target for stability
 Analysing HTTP response for anomalies
 Analysing HTTP response for potential parameter names
 Heuristic scanner found 4 parameters: _token, email, deacticvation_status, password
 Logicforcing the URL endpoint
 Encountered an error: demo.activeitzone.com

C:\Users\Pentest\Desktop\Arjun>arjun -u https://demo.activeitzone.com/matrimonial/member-listing --headers "Accept-Language: en-US\nCookie: acceptCookies=true; XSRF-TOKEN=97cXR9xxVqbLaaIn3tdhPdE6dsyTOtGCwizY0mnv; testing_session=JOiisWK9MGiiMRQPif611S8E1IMDM9kbOa4mvF7R" -oB 127.0.0.1:8080
    _
   /_| _ '
  (  |/ /(//) v2.1.51
      _/

 Probing the target for stability
 Analysing HTTP response for anomalies
 Analysing HTTP response for potential parameter names
 Heuristic scanner found 4 parameters: deacticvation_status, email, _token, password
 Logicforcing the URL endpoint
 name: _token, factor: param name reflection
 name: deacticvation_status, factor: param name reflection

C:\Users\Pentest\Desktop\Arjun>arjun -u https://demo.activeitzone.com/matrimonial/member-listing --headers "Accept-Language: en-US,en;q=0.5\nCookie: XSRF-TOKEN=2X8QbgsB7YrCbTYLC8QiPW44Diw3TSM5RdgnVrCl; testing_session=gSnyluxLaee13csXLxgJvV4apzmyPqnmBcMCqIbH; acceptCookies=true" -oB 127.0.0.1:8080
    _
   /_| _ '
  (  |/ /(//) v2.1.51
      _/

 Probing the target for stability
 Analysing HTTP response for anomalies
 Analysing HTTP response for potential parameter names
 Heuristic scanner found 4 parameters: _token, deacticvation_status, email, password
 Logicforcing the URL endpoint
 name: _token, factor: param name reflection
 name: deacticvation_status, factor: param name reflection

C:\Users\Pentest\Desktop\Arjun>

**Comment by s0md3v** [comment]
Read the docs. If you find headers option to be not working as intended, create an issue. I'm locking this thread.
