### ISSUE TITLE
Not a single domain working same error occurred every time

### ISSUE THREAD

**Issue by psycho1442** [s0md3v/Arjun#173]
![image](https://user-images.githubusercontent.com/85578072/189524602-ad23b26c-3ec5-4925-b8aa-e59f678a307a.png)

**Comment by s0md3v** [comment]
`https://www.komoot.com/endpoint` doesn't exist.

Please don't create issues if you haven't read the docs or don't know what you are doing.

**Comment by psycho1442** [comment]
I thought it worked like fuff lol that's why I add an endpoint when I saw that in usage.
