### ISSUE TITLE
False Positives in param name reflection

### ISSUE THREAD

**Issue by JM-Lemmi** [s0md3v/Arjun#175]
Params found by the heuristic scanner often claim "param name reflection", even though the word was on the page even if the param was not sent.

This could maybe be solved by checking if the string appears more times in the response, if the param is set than without.

I would be open to implementing this, but currently I'm not sure where the best location in the code would be for this check to appear.

**Comment by s0md3v** [comment]
"Heuristics" is simply a function of Arjun that extract potential parameter names from the webpage itself.
They are later verified by fuzzing and displayed if they are valid.

You are supposed to use the verified parameters, not the ones found by "Heuristics".
