### ISSUE TITLE
[Feature request] : Create a crawler/spider option

### ISSUE THREAD

**Issue by arnoldasr** [s0md3v/Arjun#176]
The tool is amazing, kudos to the developer

Would it be possible to also include a crawler/spider as well? 
So we would have a  single app for crawling and param mining all in one. IMHO it would make it huge.

Really great work and I love using Arjun.

**Comment by s0md3v** [comment]
There are plenty of crawlers that you can use get a list of links and then pass that list to Arjun.

My goal with Arjun is to do one thing and do it well i.e. parameter bruteforcing. Such additional functionality will only make the development hard.
