### ISSUE TITLE
Encounter an error

### ISSUE THREAD

**Issue by psycho1442** [s0md3v/Arjun#180]
When i give arjun a file with urls, arjun encounter an error after checking 17/3776 urls.It will be helpful if you fix it or help me to fix it.![image](https://user-images.githubusercontent.com/85578072/194742220-ac4eeb4f-3086-456d-aff8-479ff010900e.jpeg)

**Comment by psycho1442** [comment]
![image](https://user-images.githubusercontent.com/85578072/194763254-5ea49cb5-34aa-448f-a425-fea8cbaeb295.jpeg)

**Comment by s0md3v** [comment]
You are using version `2.2.0`, current version is `2.2.1` and this bug is fixed already afaik. Update your installation.
