### ISSUE TITLE
multiple problem

### ISSUE THREAD

**Issue by Phoenix1112** [s0md3v/Arjun#184]
problem-1

When I want to use arjun with the -oT parameter, arjun does not give an output without scanning all the url addresses in my url list. really this is a big problem. I am running the arjun program on 500 url addresses, after 250 successful url addresses, when arjun starts scanning a url address that will terminate or stop the program, the program terminates without output because there is no output of the previously scanned url addresses. After arjun scans each new url address, if it finds a parameter, it should save it as output and start scanning the next url address.

problem-2

the latest version of arjun, it seems as if it scans much faster than the old version. that's why I see a lot of "Encountered an error" errors. Even if I use the -t 1 and -c 1 parameters, I get the "Encountered an error" error. When this situation became too much in the new version, I installed the old version arjun and when I tested on the same site, arjun finished the scan without any errors.

problem-3

Some url addresses may have extensions such as ".pptx, .potm". arjun seems to freeze while testing these extensions. Arjun needs to filter while testing url addresses with such extensions, and if there are url addresses with similar extensions, it should pass. or a feature should be added to understand that arjun cannot test against url addresses in this extension.

example-target: ```https://graduate.utdallas.edu/docs/On-Line%20Personal%20Branding.pptx```

**Comment by huntergregal** [comment]
What version worked for you?

**Comment by s0md3v** [comment]
1. Fixed
2. I have tested arjun over time and it seems to be working for me. If there are any cases of this you encounter where the older versions gives results but this doesn't, i'll be happy to take a look.
3. Fixed
