### ISSUE TITLE
gets stuck on some working link

### ISSUE THREAD

**Issue by ghost** [s0md3v/Arjun#186]
Hi brother, it's been like this for hours but the link works. Can you tell me why or fix it by skipping the url when this happens? If a list is passed, it can't be locked like this forever

[*] Scanning 56/591: https://***.***.com/***/**/****/3476.png
[*] Probing the target for stability

**Comment by s0md3v** [comment]
I will think about what to do about this but why are you scanning a png file? :/

**Comment by s0md3v** [comment]
Arjun now skips any urls that aren't webpages e.g. png files etc.
