### ISSUE TITLE
File not found '/root/tools/Arjun/arjun.py

### ISSUE THREAD

**Issue by dirtycoder0124** [s0md3v/Arjun#192]
I installed Arjun using
```
python3 setup.py install
```
After successful installation. I run the arjun and it gives error 
![image](https://user-images.githubusercontent.com/16449867/219563206-1e562149-215a-4352-9e75-35084369e8f5.png)

**Comment by s0md3v** [comment]
Just tried it, it works on my machine.

This is a env specific issue. Everyone's system configuration is different; users are supposed to find a solution on their own.

Closing.
