### ISSUE TITLE
Error execution "ModuleNotFoundError: No module named 'idna'"

### ISSUE THREAD

**Issue by tXambe** [s0md3v/Arjun#193]
Hello,

when I run arjun I have this error "ModuleNotFoundError: No module named 'idna'
" but this module is installed.

Can anyone help me ?

A greeting and thanks

**Comment by s0md3v** [comment]
This is an error regarding an dependency; users are supposed to figure this out on their own. Everyone's system configuration is different and developers are not paid to provide customer support.

Closing.
