### ISSUE TITLE
It wants the --stable command to be used on all scans

### ISSUE THREAD

**Issue by Phoenix1112** [s0md3v/Arjun#196]
I was not having such a problem when using previous arjun versions. I just run arjun with normal command.

```
arjun -u https://example.com/xxxx.php
```

```
   /_| _ '
  (  |/ /(//) v2.2.1
      _/

[*] Probing the target for stability
[*] Analysing HTTP response for anomalies
[*] Analysing HTTP response for potential parameter names
[*] Logicforcing the URL endpoint
[-] Target is misbehaving. Try the --stable swtich.
[!] No parameters were discovered.
```

but when I try with other arjun versions, it does not give such an output and shows a few parameter outputs.  You will suggest I use the -c parameter, but I see the same result on all sites. arjun shows the same behavior even if there is no blocking on the site.

**Comment by X05qqqq69** [comment]
have you found any workaround ? cause this happens to me too ?

**Comment by deep1chil** [comment]
help us
