### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by Arlissonjaques** [s0md3v/Arjun#207]
Hello,

I hope everything is going well!

Recently, when updating to the latest version, I noticed a change in the license, which apparently was switched from GPL to AGPL. However, I observed that the setup.py file still references GPL. I would like to know if this difference was intentional and if there has been consideration for updating the setup.py file to reflect the new license.

Could you clarify which license you intend to use going forward?

**Comment by Arlissonjaques** [comment]
Thank you for responding @s0md3v.

Actually, I have no interest in using it commercially. I'm actually updating this package on Debian, and these licensing issues are important, so it's been a roadblock.

When you can, could you update this information so that the package can also be updated on Debian?

**Comment by s0md3v** [comment]
@Arlissonjaques Done! Thanks for the heads up.
