### ISSUE TITLE
I am having a problem while running arjun tool

### ISSUE THREAD

**Issue by psych4cker** [s0md3v/Arjun#214]
When I am running the simple command "arjun -u https://target.com" It is showing me an error

![Screenshot 2024-08-03 135254](https://github.com/user-attachments/assets/803c8190-f653-48f1-9c2d-f3daba2078ae)

How can I fix that!! 
Plzz help!!

**Comment by s0md3v** [comment]
Is it possible for you to share the target with my privately?

Both my email and twitter are linked in my github profile.

**Comment by psych4cker** [comment]
I have dmed you on twitter

**Comment by s0md3v** [comment]
That website is refusing connections because the default user-agent used by arjun is not of a browser. They have likely done so to stop bots and such.

I will push a workaround in the next update. Meanwhile, you can add your browser's user agent in the headers.

**Comment by psych4cker** [comment]
Still it is showing error even after adding headers
and I tried the same command twice and both times the result were different

1st time
![Screenshot 2024-08-03 205627](https://github.com/user-attachments/assets/9a54379b-2882-40f3-b6d5-c94225efa5cf)

2nd time
![Screenshot 2024-08-03 205900](https://github.com/user-attachments/assets/a475a418-0eeb-485e-91ba-2b77b99e69dc)

**Comment by s0md3v** [comment]
The problem was actually caused by using http instead https.
