### ISSUE TITLE
Quit() stops progress when using target list

### ISSUE THREAD

**Issue by YouGina** [s0md3v/Arjun#32]
The quit() function on the following line stops the program:
https://github.com/s0md3v/Arjun/blob/a4d095ccfe99e609900b69ddedf440fdff532201/core/utils.py#L72-L73

Also when you're using a list of urls using the --urls parameter and a file with urls. This causes the progress to be lost.

**Comment by s0md3v** [comment]
Thanks for bringing this to my attention. I feel very stupid rn.

**Comment by YouGina** [comment]
Not necessary, such things can happen ¯\_(ツ)_/¯
