### ISSUE TITLE
Regex initilized but not used

### ISSUE THREAD

**Issue by bugbaba** [s0md3v/Arjun#34]
Hi s0md3v,

The `method` variable on https://github.com/s0md3v/Arjun/blob/master/arjun.py#L103 to get all the method in the form tag, But it wasn't used anywhere in the code later.

--
Regards,
bugbaba

**Comment by s0md3v** [comment]
That code snippet was copied from my another project named[Zetanize](https:///gihutb.com/s0md3v/zetanize) and the variable `method` has no use in Arjun an should be removed in the next update.
