### ISSUE TITLE
Can you add proxy support to this?

### ISSUE THREAD

**Issue by jakjs21jdkw** [s0md3v/Arjun#39]
It would be great if you could proxy the requests through another tool to see what is going on and what executed on the endpoint.

**Comment by shaunpud** [comment]
This uses the requests library which supports proxies out of the box;
https://requests.readthedocs.io/en/master/user/advanced/#proxies

`HTTP_PROXY=host:port python arjun.py ...`

**Comment by BreakfastSerial** [comment]
What approach would you recommend on Windows systems?
