### ISSUE TITLE
Pushlish on PyPI

### ISSUE THREAD

**Issue by fabaff** [s0md3v/Arjun#40]
There was https://github.com/s0md3v/Arjun/pull/22 which you trashed two times. I just wanted to thanks you for wasting my time. 

But it's good to see that you take donations now to "encourage me to contribute more to the open source".

**Comment by s0md3v** [comment]
I value your contributions but I didn't want to publish it on PyPi. Check out my other projects, they are not on PyPi either. It would have been much better for both of us if you opened an issue first.

[Read this tweet](https://twitter.com/s0md3v/status/1186934746065989632), there will be an Arjun 2.0 which will be a library and will be published to PyPi. I will fix conflicts and merge your PR to make sure you get credits for your work.

**Comment by fabaff** [comment]
I opened a PR to get it done and offered to maintain it. Opening issue to wait a couple of weeks for feedback doesn't get things done.

Ok, then I open issues.
