### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by mayurgupta1411** [s0md3v/Arjun#44]
every time i got this error .
please look at screenshot [https://drive.google.com/file/d/15ivIm_Dfqwstzb_K8zc2lH99_LWMZCWZ/view?usp=sharing](url)

**Comment by mayurgupta1411** [comment]
https://drive.google.com/file/d/15ivIm_Dfqwstzb_K8zc2lH99_LWMZCWZ/view?usp=sharing

**Comment by EulerIExponent** [comment]
Maybe you are using python version <3.4 
Check your python version

**Comment by EulerIExponent** [comment]
Arjun doesn't work with python < 3.4  , check your python version and try again
