### ISSUE TITLE
Identifying params like debug=1 and admin=yes which has not a random value

### ISSUE THREAD

**Issue by maverickNerd** [s0md3v/Arjun#45]
As mentioned in the working of Arjun point 2, A second request to the URL is made but this time, a randomly generated parameter, this means that Arjun currently sends a random value with each parameter to identify any change in response.

But sometimes there can be other valid params that are missed by this approach.

Params like debug=1, admin=true, admin=yes.

More params are mentioned here: https://github.com/yehgdotnet/data-payloads/blob/master/params/debug_params.txt

It would be beneficial if with the current (-f) option of passing wordlist, we can pass a wordlist like the one above and Arjun can decide a valid param by looking at the change in response which Arjun is already capable of doing.

**Comment by s0md3v** [comment]
This is now supported by default in Arjun v2.2.0 🎉 

Thanks for the suggestion and being patient for 2 years!
