### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by AlessandroZ** [s0md3v/Arjun#46]
Hi @s0md3v, 

Using your last version, I had this stracktrace.
```
    _         
   /_| _ '    
  (  |/ /(//) v1.6
      _/      

[~] Analysing the content of the webpage
[~] Analysing behaviour for a non-existent parameter
[!] Reflections: 0
[!] Response Code: 200
[!] Content Length: 21174
[!] Plain-text Length: 8487
[~] Parsing webpage for potential parameters
Traceback (most recent call last):
  File "./arjun.py", line 237, in <module>
    finalResult[url] = initialize(url, include, headers, GET, delay, paramList, threadCount)
  File "./arjun.py", line 200, in initialize
    heuristic(firstResponse.text, paramList)
  File "./arjun.py", line 122, in heuristic
    print('%s Heuristic found a potential %s parameter: %s%s%s' % (good, method.group(1), green, inpName, end))
AttributeError: 'NoneType' object has no attribute 'group'
```
I didn't take the time to do a good PR, I'm sorry. 

However, the problem occurs [here](https://github.com/s0md3v/Arjun/blob/master/arjun.py#L110) (because `method` is None) so the [print](https://github.com/s0md3v/Arjun/blob/master/arjun.py#L122) fails.  

Thanks a lot for all your projects and work, I which you a happy new year ;)

**Comment by zer0dots** [comment]
same

[~] Parsing webpage for potential parameters
Traceback (most recent call last):
  File "arjun.py", line 245, in <module>
    finalResult[url] = initialize(url, include, headers, GET, delay, list(paramList), threadCount)
  File "arjun.py", line 199, in initialize
    heuristic(firstResponse.text, paramList)
  File "arjun.py", line 121, in heuristic
    print('%s Heuristic found a potential %s parameter: %s%s%s' % (good, method.group(1), green, inpName, end))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by AlessandroZ** [comment]
I forgot to specify that when it failed a good parameter was found. So the print should still be done, otherwise we loose good results. 

A dirty patch could be done like so: 
```
if method:
    print('%s Heuristic found a potential %s parameter: %s%s' % (good, green, inpName, end))
else:
    print('%s Heuristic found a potential %s parameter: %s%s%s' % (good, method.group(1), green, inpName, end))
```

**Comment by zer0dots** [comment]
Thanks @AlessandroZ

**Comment by s0md3v** [comment]
Potentially fixed in latest release. Closing until it's reproduced.
