### ISSUE TITLE
--include option and URL encoded parameters

### ISSUE THREAD

**Issue by Techbrunch** [s0md3v/Arjun#47]
Hello,

I'm trying to bruteforce GET parameters of an endpoint that requires a key for authentication. The value is an ID that is base64 encoded:

This is the command I'm using:

```
python arjun.py -u https://taget.com/endpoint --get --include 'key=MTIzNDU2Nzg5MDEyMzQ%3D'
```

The problem is that the "%" is URL encoded again when doing the request.

To solve this I used this solution:

```python
def requester(url, data, headers, GET, delay):
    data = "&".join("%s=%s" % (k,v) for k,v in data.items())
```

Source: https://stackoverflow.com/a/23497912

Thanks for the tool !

**Comment by s0md3v** [comment]
You should replace "%3D" with the decoded version i.e. "=".
