### ISSUE TITLE
[BUG] High Number of Redirections Stops Execution of Arjun

### ISSUE THREAD

**Issue by ngkogkos** [s0md3v/Arjun#51]
In some cases websites will end up redirecting multiple times, for which Python has an internal limit and raises an exception. Because this is not handled, it would forcily exit and stop the execution of arjun especially if running it with a big URLs list, example:

```
/arjun  $ python3 ~/Tools/Arjun/arjun.py -f ./u_params.txt -t 50 -o arjun_url_params_report.txt --urls ../all_urls.txt --get 

[~] Scanning: http://REMOVED.COM
[~] Analysing the content of the webpage
Traceback (most recent call last):
  File "/root/Tools/Arjun/arjun.py", line 246, in <module>
    finalResult[url] = initialize(url, include, headers, GET, delay, list(paramList), threadCount)
  File "/root/Tools/Arjun/arjun.py", line 172, in initialize
    firstResponse = requester(url, include, headers, GET, delay)
  File "/root/Tools/Arjun/core/requester.py", line 20, in requester
    response = requests.get(url, params=data, headers=headers, verify=False)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

I was able to quickly patch this by editing how GET requests are performed in the `requester.py` file and have it retry without following redirections if it fails:

/Arjun/core/requester.py
```

    if GET:
        try:
            response = requests.get(url, params=data, headers=headers, verify=False)
        except:
            response = requests.get(url, params=data, headers=headers, verify=False, allow_redirects=False)
```

This is probably not an ideal solution and that is why I did not open a merge request, but I am leaving this here as a temporary solution until this is patched.

Thanks for your work on this.

**Comment by s0md3v** [comment]
It's not a commercial product made for people with all kind of knowledge levels.

This tool is meant to be used by people who understand security and everything, that means, it's upto the user to supply a working URL.

However, I will still patch this in the next release as it can break the functionality in case of mass bruteforcing.

**Comment by adik69** [comment]
It also happens that when provided list of urls , If there is one "URL" which is causing bad requests , the arjun simply exits without saving all the previous data that has been collected.
