### ISSUE TITLE
error scan import file

### ISSUE THREAD

**Issue by marz-hunter** [s0md3v/Arjun#53]
root@zhack-vps:~/Arjun# python3 arjun.py --urls myurl --get -t 22
    _
   /_| _ '
  (  |/ /(//) v1.6
      _/

[~] Scanning: http://domain:80/en/url=
[~] Analysing the content of the webpage
Traceback (most recent call last):
  File "arjun.py", line 246, in <module>
    finalResult[url] = initialize(url, include, headers, GET, delay, list(paramList), threadCount)
  File "arjun.py", line 172, in initialize
    firstResponse = requester(url, include, headers, GET, delay)
  File "/root/Arjun/core/requester.py", line 20, in requester
    response = requests.get(url, params=data, headers=headers, verify=False)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by bitcoin-management-group** [comment]
i got the same error when i tried to scan url that redirected to another url

**Comment by theleecher** [comment]
I have the same error, when i use with the opttion **--urls**

> [~] Analysing the content of the webpage
> Traceback (most recent call last):
>   File "arjun.py", line 237, in <module>
>     finalResult[url] = initialize(url, include, headers, GET, delay, paramList, threadCount)
>   File "arjun.py", line 172, in initialize
>     firstResponse = requester(url, include, headers, GET, delay)
>   File "/opt/Tools/Web/Arjun/core/requester.py", line 20, in requester
>     response = requests.get(url, params=data, headers=headers, verify=False)
>   File "/home/hawk/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
>     return request('get', url, params=params, **kwargs)
>   File "/home/hawk/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/home/hawk/.local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/hawk/.local/lib/python3.8/site-packages/requests/sessions.py", line 665, in send
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/home/hawk/.local/lib/python3.8/site-packages/requests/sessions.py", line 665, in <listcomp>
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/home/hawk/.local/lib/python3.8/site-packages/requests/sessions.py", line 166, in resolve_redirects
>     raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
> requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
>
