### ISSUE TITLE
Dissecting how Arjun works!

### ISSUE THREAD

**Issue by ParikhKadam** [s0md3v/Arjun#55]
This is not about any bug/feature, I just want to confirm what I understood after going through the source.

1. There's a huge list of params which we are gonna try on a url.
2. We try a random param in order to get if the server response to random params by comparing the length of data returned with the length of data returned by a normal query.
3. Then we divide the list of params into sublists of 50 and try each one out.
4. For each sublist we check that the length of data returned is not same as the one when we tried randomly i.e. these params are causing the content inside response to change. We also check that number of reflections are not same for the same purpose.
5. If the params cause a change in response's content, we divide the sublist of 50 into further sublists of 2, to find out specifically that which param(s) caused this change.
6. Then after we get a list of params that were responsible for change in content length and also had relfections, we run a loop over all and cross verify the same in order to obtain the final list of params.

That's all..

Is this the same logic you wrote? I just want to confirm it. Thank you..

**Comment by s0md3v** [comment]
You got the point.

https://github.com/s0md3v/Arjun/wiki/How-Arjun-works%3F
