### ISSUE TITLE
Support no HTTP/S

### ISSUE THREAD

**Issue by gbiagomba** [s0md3v/Arjun#57]
Hello,

This is more of a request than "bug", but it would be great if i could feed in a target file without specifying http/s and the script should automatically try to connect over both unless the user specifics otherwise. A user should be able to specify a flag like "--assume-http" or "--assume-https" to have the script try http/s respectively.

**Comment by s0md3v** [comment]
This does not align with the vision of Arjun. Thanks for the suggestion.
