### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by AbdulrahemKhan** [s0md3v/Arjun#58]
I'm trying to use Arjun but this is coming 

Traceback (most recent call last):
  File "http://arjun.py", line 26, in <module>
    from core.requester import requester
  File "/root/Arjun/core/requester.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

BTW I'm using python 3.8.3

<a href="https://imgbb.com/"><img src="https://i.ibb.co/zxPTvZw/image.png" alt="image" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/6mpYMmF/image.png" alt="image" border="0"></a>

**Comment by VainlyStrain** [comment]
You'll need to install the Python Requests library
```
$ pip install requests --user
```
Cheers

**Comment by Be1nna** [comment]
I wrote this command, but I'm getting the same error.

**Comment by VainlyStrain** [comment]
Are you using Kali? AFAIK, it still has python2 as default version, so you might need to use pip3.

Check `pip --version`. If it says Python2, you need to use pip3 (or a similar command).

**Comment by Be1nna** [comment]
Thanks
