### ISSUE TITLE
Struck at "narrower" function

### ISSUE THREAD

**Issue by Raywando** [s0md3v/Arjun#60]
My query: 
`python3 ~/toys/Arjun/arjun.py -u http://somedomain.com/static/sites/xxxx/header-footer/1.4/js/loader.js -f ~/toys/Arjun/db/params.txt -o arjun_out`

The progress was stuck after 
`[~] Performing heuristic level checks`

I'm not the best in Python so I was not sure whats the problem, but I was able to trace the issue back to the "enumerate" function in "narrower"

![WindowsTerminal_6EydNq9tPc](https://user-images.githubusercontent.com/33800255/83375145-9963ba00-a3d6-11ea-84c9-fe8b39721d35.png)

**Comment by s0md3v** [comment]
Potentially fixed in latest release. Closing until it's reproduced.
