### ISSUE TITLE
The specified file for parameters doesn't exist

### ISSUE THREAD

**Issue by yassinek3ch** [s0md3v/Arjun#66]
**i'm trying to run in on windows i got the error**

```
C:\Users\Yassine Benfakih\Desktop\Bugbounty\MybugBounty-Tool\python3

> python.exe ..\Arjun\arjun.py --url https://bugbountysite.ma/ --get
    _
   /_| _ '
  (  |/ /(//) v1.6
      _/

 The specified file for parameters doesn't exist  

```
**any help ?**

**Comment by Iamstanlee** [comment]
Here's the path the url wordlist "https://github.com/s0md3v/Arjun/blob/master/db/params.txt"
save it to your machine and rerun 
```> python.exe ..\Arjun\arjun.py --url https://bugbountysite.ma/ --get -f params.txt```

**Comment by gbiagomba** [comment]
that fixed the error for me @Iamstanlee

**Comment by s0md3v** [comment]
Fixed.
