### ISSUE TITLE
Suggestion: separate post params and get params in output

### ISSUE THREAD

**Issue by Raywando** [s0md3v/Arjun#68]
Hi, first of all, thanks for the amazing tool!

I usually use the tool using both `--post` and `--get` arguments, it would be cool to know which is which in the output. Because it prints all the parameters in the output but I don't get information about which is get params and which is post params. (Not sure if `--post` and `--get` work together this way, but if not, here is another idea! xD)

Thanks!

**Comment by s0md3v** [comment]
Done.
