### ISSUE TITLE
Getting error message URI too large

### ISSUE THREAD

**Issue by H04Xed** [s0md3v/Arjun#71]
This is an awesome tool however it doesn't seem to work on modern websites due to arjun inserting too many params in one request that the back-end server rejects it, is there a way i can limit that? when I cut it in half it still works but is there a way not to do this manually?

**Comment by JimmyHurrah** [comment]
The initial batch size is set here https://github.com/s0md3v/Arjun/blob/6260fc67c6d654aade029b73023f2420f90926bd/arjun.py#L208 if you change that, 50,  To something larger, ie 100, You will get more groups with fewer parameters in each.

**Comment by H04Xed** [comment]
Thank you so much!
