### ISSUE TITLE
ModuleNotFoundError: No module named 'plugins.otx'

### ISSUE THREAD

**Issue by xaeroborg** [s0md3v/Arjun#87]
I am getting this error with anything I do. 
`Python version: 3.8.2`
`uname -a: Linux kali 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux` 
![image](https://user-images.githubusercontent.com/33274680/101286699-fa22e380-37b9-11eb-8b39-9d5a8913a634.png)

**Comment by s0md3v** [comment]
I am unable to reproduce this. Can you please re-clone the repo and share the list of files within `/Arjun/plugins`?

**Comment by xaeroborg** [comment]
Here it is
![image](https://user-images.githubusercontent.com/33274680/101321416-530e7c80-388b-11eb-9c9e-37bf21c5c491.png)

**Comment by xaeroborg** [comment]
I have even tried rm -rf Arjun and then git clone https://github.com/s0md3v/Arjun.git
Then ran python3 arjun.py --help and it shows the same error.

**Comment by s0md3v** [comment]
Okay, I made a change which should fix it. Please try it one last time.

**Comment by xaeroborg** [comment]
Now it works like a charm. Thanks for getting it done. 
![image](https://user-images.githubusercontent.com/33274680/101362329-faa8a080-38c5-11eb-9854-d5382ef55281.png)

May I know what the change you made?

**Comment by xaeroborg** [comment]
I think adding __init__.py did the work, right?

**Comment by s0md3v** [comment]
yes
