### ISSUE TITLE
 [Improvement] Some reflections are missing from results 

### ISSUE THREAD

**Issue by TvMpt** [s0md3v/Arjun#90]
Hi,
In a page with "script" parameter reflected and vulnerable to XSS, the arjun seems not identify it as a possible issue.
Example:
www.example.com/?script=qwerty
will render in page as  _<script type='text/javascript' src='/xxxxx**qwerty**.js'></script>_
Isn't supposed to match the random string from parameter value even if is appended with other strings?

Love your apps, thank you.

**Comment by s0md3v** [comment]
Yes, it is supposed to match them.

Is it possible for you to share that URL with me? You can DM me on [twitter](https://twitter.com/s0md3v) or mail me at s0md3v[at]gmail.com

Thanks for reporting this issue.

**Comment by s0md3v** [comment]
This issue has been fixed, thanks for reporting.

I noticed some unusual behavior from the endpoint your DMed me on twitter and Arjun got some false negatives for it but that's another issue to solve.
