### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by Smismi11** [s0md3v/Arjun#91]
Hi,

when using a small wordlist (23 words in my case) I get an exception:

[*] Logicforcing the URL endpoint
Traceback (most recent call last):
  File "/home/Smismi/git/Arjun/arjun.py", line 172, in <module>
    these_params = initialize(request, wordlist)
  File "/home/Smismi/git/Arjun/arjun.py", line 146, in initialize
    param_groups = slicer(populated, int(len(wordlist)/args.chunks))
  File "/home/Smismi/git/Arjun/core/utils.py", line 63, in slicer
    k, m = divmod(len(dic), n)
ZeroDivisionError: integer division or modulo by zero

I think the problem exists because int(len(wordlist)/args.chunks) is set to 0 when len(wordlist) is smaller than 500.

**Comment by s0md3v** [comment]
Thanks for reporting this issue, it has been fixed.

Now, if you choose a wordlist with < 500 words, Arjun will set the chunk size to half of your wordlist by default.

**Comment by Smismi11** [comment]
Wow, that was fast. Thank you :+1:
