### ISSUE TITLE
Error collect parameters from passive source

### ISSUE THREAD

**Issue by Be1nna** [s0md3v/Arjun#93]
I use the feature of collecting parameters from passive source as follows;

python arjun.py -passive example.com

it is written on the screen that the parameters are collected and added to the word list, but there is no change in the word list.

**Comment by s0md3v** [comment]
The collected parameters are added to the wordlist in this line: https://github.com/s0md3v/Arjun/blob/76012cbd8c8174436a732613ea6b7717d27e8efb/arjun.py#L68

Did you mean Arjun found 0 parameters from passive sources?

**Comment by s0md3v** [comment]
`--passive` option doesn't actually save the parameters it finds to the wordlist file, it only includes them for the current scan.

**Comment by Be1nna** [comment]
Is there any option I can save to wordlist file?

**Comment by s0md3v** [comment]
Not right now.

I might add a `--passive-save` option in next release, thanks for asking.

**Comment by Be1nna** [comment]
Thank you for your quick reply
